apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
  namespace: social-media
data:
  NODE_ENV: "production"
  PORT: "4004"

  DB_HOST: "chat-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "chat-db"

  REDIS_URL: "redis://redis-cache:6379"

  SERVICE_NAME: "chat-service"
  LOG_LEVEL: "warn"
  SALT_ROUNDS: "10"