apiVersion: v1
kind: ConfigMap
metadata:
  name: post-service-config
  namespace: social-media
data:
  NODE_ENV: "production"
  PORT: "4003"

  DB_HOST: "post-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "post-db"

  REDIS_URL: "redis://redis-cache:6379"
  KAFKA_BROKERS: "kafka-0.kafka-headless:9092"

  SERVICE_NAME: "post-service"
  LOG_LEVEL: "warn"