apiVersion: v1
kind: ConfigMap
metadata:
  name: post-service-config
  namespace: social-media
data:
  NODE_ENV: "production"
  PORT: "4003"

  DB_HOST: "post-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "post-db"

  REDIS_URL: "redis://redis-cache:6379"
  KAFKA_BROKERS: "kafka-0.kafka-headless:9092"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"

  SERVICE_NAME: "post-service"
  LOG_LEVEL: "warn"

  POST_FEED_RATE_LIMIT_WINDOW_SECONDS: "60"
  POST_FEED_RATE_LIMIT_MAX_REQUESTS: "180"
  POST_WRITE_RATE_LIMIT_WINDOW_SECONDS: "60"
  POST_WRITE_RATE_LIMIT_MAX_REQUESTS: "30"
  POST_ENGAGEMENT_RATE_LIMIT_WINDOW_SECONDS: "60"
  POST_ENGAGEMENT_RATE_LIMIT_MAX_REQUESTS: "120"
