apiVersion: v1
kind: ConfigMap
metadata:
  name: social-graph-service-config
  namespace: social-media
data:
  NODE_ENV: "production"
  PORT: "4005"
  
  DB_HOST: "social-graph-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "social-graph-db"

  SERVICE_NAME: "social-graph-service"
  LOG_LEVEL: "warn"