apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: social-media
data:
  NODE_ENV: "production"
  PORT: "4001"

  DB_HOST: "user-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "user-db"

  REDIS_URL: "redis://redis-cache:6379"
  KAFKA_BROKERS: "kafka-0.kafka-headless:9092"

  SERVICE_NAME: "user-service"
  LOG_LEVEL: "warn"
  SALT_ROUNDS: "10"