apiVersion: v1
kind: ConfigMap
metadata:
  name: web-gateway-config
  namespace: social-media
data:
  NODE_ENV: "production"
  PORT: "8088"

  REDIS_URL: "redis://redis-cache:6379"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"

  USER_SERVICE_URL: "http://user-service:4001"
  MEDIA_SERVICE_URL: "http://media-service:4002"
  POST_SERVICE_URL: "http://post-service:4003"
  CHAT_SERVICE_URL: "http://chat-service:4004"
  SOCIAL_GRAPH_SERVICE_URL: "http://social-graph-service:4005"

  SERVICE_NAME: "web-gateway"
  LOG_LEVEL: "warn"
