apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: web-gateway
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 400m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: user-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: media-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: post-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: chat-service
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 600m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: social-graph-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
