apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - storage/aws-gp3-storageclass.yaml

patches:
  - path: patches/configmap-aws-production.yaml
  - path: patches/application-replicas-aws-production.yaml
  - path: patches/application-resources-aws-production.yaml
  - path: patches/database-storage-aws-production.yaml
  - path: patches/kafka-storage-aws-production.yaml
  - path: ingress/alb-ingress-aws-production.yaml

images:
  - name: social-media/web-gateway
    newName: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/social-media/web-gateway
    newTag: production-CHANGE_ME_IMAGE_TAG
  - name: social-media/user-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/social-media/user-service
    newTag: production-CHANGE_ME_IMAGE_TAG
  - name: social-media/media-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/social-media/media-service
    newTag: production-CHANGE_ME_IMAGE_TAG
  - name: social-media/post-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/social-media/post-service
    newTag: production-CHANGE_ME_IMAGE_TAG
  - name: social-media/chat-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/social-media/chat-service
    newTag: production-CHANGE_ME_IMAGE_TAG
  - name: social-media/social-graph-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/social-media/social-graph-service
    newTag: production-CHANGE_ME_IMAGE_TAG
