apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: social-media
  labels:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 4004
      targetPort: http
