apiVersion: v1
kind: Service
metadata:
  name: social-graph-service
  namespace: social-media
  labels:
    app.kubernetes.io/name: social-graph-service
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: social-graph-service
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 4005
      targetPort: http
