apiVersion: v1
kind: Service
metadata:
  name: web-gateway
  namespace: social-media
  labels:
    app.kubernetes.io/name: web-gateway
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-gateway
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 8088
      targetPort: http
