apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/configmap-local.yaml
  - path: patches/ingress-local.yaml
  - path: patches/application-replicas-local.yaml
  - path: patches/database-storage-local.yaml
  - path: patches/kafka-local.yaml

images:
  - name: social-media/web-gateway
    newTag: local
  - name: social-media/user-service
    newTag: local
  - name: social-media/media-service
    newTag: local
  - name: social-media/post-service
    newTag: local
  - name: social-media/chat-service
    newTag: local
  - name: social-media/social-graph-service
    newTag: local
