apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: web-gateway
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 800m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: user-service
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 768Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: media-service
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 768Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: post-service
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 768Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: chat-service
          resources:
            requests:
              cpu: 300m
              memory: 384Mi
            limits:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-service
  namespace: social-media
spec:
  template:
    spec:
      containers:
        - name: social-graph-service
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 768Mi
