apiVersion: v1
kind: ConfigMap
metadata:
  name: social-media-config
  namespace: social-media
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  APP_ENV: "digitalocean-production"
  REDIS_URL: "redis://redis-cache:6379"
  KAFKA_BROKERS: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092"
