apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-data
  namespace: social-media
spec:
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-db-data
  namespace: social-media
spec:
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-db-data
  namespace: social-media
spec:
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-graph-db-data
  namespace: social-media
spec:
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 30Gi
