apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: social-media
spec:
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        storageClassName: do-block-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
