FROM node:22
WORKDIR /app

# Install dependencies first (cached)
COPY package*.json ./
RUN npm ci

# Copy the rest of source code
COPY . .

# Build TypeScript → JS
RUN npm run build

ENV NODE_ENV=development

EXPOSE 4002

CMD ["node", "dist/server.js"]