apiVersion: v1
kind: ConfigMap
metadata:
  name: social-media-config
  namespace: social-media
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  WEB_GATEWAY_PORT: "8088"
  
  MEDIA_SERVICE_PORT: "4002"
  POST_SERVICE_PORT: "4003"

  SOCIAL_GRAPH_SERVICE_PORT: "4005"
  
  MEDIA_SERVICE_URL: "http://media-service:4002"
  POST_SERVICE_URL: "http://post-service:4003"

  SOCIAL_GRAPH_SERVICE_URL: "http://social-graph-service:4005"
  REDIS_URL: "redis://redis-cache:6379"
  KAFKA_BROKERS: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092"
  
  POST_DB_HOST: "post-db"
  
  SOCIAL_GRAPH_DB_HOST: "social-graph-db"
  DB_PORT: "5432"
