apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: social-media

resources:
  - namespace.yaml
  - configmaps/user-service-configmap.yaml
  - configmaps/post-service-configmap.yaml
  - configmaps/chat-service-configmap.yaml
  - configmaps/media-service-configmap.yaml
  - configmaps/social-graph-service-configmap.yaml
  - configmaps/web-gateway-configmap.yaml
  - secrets/user-service-secret.yaml
  - secrets/post-service-secret.yaml
  - secrets/chat-service-secret.yaml
  - secrets/media-service-secret.yaml
  - secrets/social-graph-service-secret.yaml
  - databases/user-db.yaml
  - databases/post-db.yaml
  - databases/chat-db.yaml
  - databases/social-graph-db.yaml
  - databases/redis-cache.yaml
  - databases/kafka.yaml
  - deployments/web-gateway.yaml
  - deployments/user-service.yaml
  - deployments/media-service.yaml
  - deployments/post-service.yaml
  - deployments/post-service-worker.yaml
  - deployments/chat-service.yaml
  - deployments/social-graph-service.yaml
  - services/web-gateway.yaml
  - services/user-service.yaml
  - services/media-service.yaml
  - services/post-service.yaml
  - services/chat-service.yaml
  - services/social-graph-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: social-media-platform
