apiVersion: v1
kind: Secret
metadata:
  name: social-media-secret
  namespace: social-media
type: Opaque
stringData:
  JWT_SECRET: ""
  SALT_ROUNDS: "10"
  USER_POSTGRES_DB: ""
  USER_POSTGRES_USER: ""
  USER_POSTGRES_PASSWORD: ""
  USER_DATABASE_URL: ""
  POST_POSTGRES_DB: ""
  POST_POSTGRES_USER: ""
  POST_POSTGRES_PASSWORD: ""
  POST_DATABASE_URL: ""
  CHAT_POSTGRES_DB: ""
  CHAT_POSTGRES_USER: ""
  CHAT_POSTGRES_PASSWORD: ""
  CHAT_DATABASE_URL: ""
  SOCIAL_GRAPH_POSTGRES_DB: ""
  SOCIAL_GRAPH_POSTGRES_USER: ""
  SOCIAL_GRAPH_POSTGRES_PASSWORD: ""
  SOCIAL_GRAPH_DATABASE_URL: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""