apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secret
  namespace: social-media
type: Opaque
stringData:
  JWT_SECRET: ""
  CHAT_POSTGRES_DB: ""
  CHAT_POSTGRES_USER: ""
  CHAT_POSTGRES_PASSWORD: ""
  CHAT_DATABASE_URL: ""
