apiVersion: v1
kind: Secret
metadata:
  name: media-service-secret
  namespace: social-media
type: Opaque
stringData:
  JWT_SECRET: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
