apiVersion: v1
kind: Secret
metadata:
  name: post-service-secret
  namespace: social-media
type: Opaque
stringData:
  JWT_SECRET: ""
  POST_POSTGRES_DB: ""
  POST_POSTGRES_USER: ""
  POST_POSTGRES_PASSWORD: ""
  POST_DATABASE_URL: ""
