apiVersion: v1
kind: Secret
metadata:
  name: social-graph-service-secret
  namespace: social-media
type: Opaque
stringData:
  SOCIAL_GRAPH_POSTGRES_DB: ""
  SOCIAL_GRAPH_POSTGRES_USER: ""
  SOCIAL_GRAPH_POSTGRES_PASSWORD: ""
  SOCIAL_GRAPH_DATABASE_URL: ""
