apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: social-media
type: Opaque
stringData:
  JWT_SECRET: ""
  SALT_ROUNDS: "10"
  USER_POSTGRES_DB: ""
  USER_POSTGRES_USER: ""
  USER_POSTGRES_PASSWORD: ""
  USER_DATABASE_URL: ""
