ALTER TYPE "OutboxEventStatus" ADD VALUE IF NOT EXISTS 'DEAD_LETTERED';

ALTER TABLE "OutboxEvent"
  ADD COLUMN IF NOT EXISTS "processingStartedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "deadLetteredAt" TIMESTAMP(3);
